<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function findSoMuchFormTheLast()
	{
		$qb = $em->createQueryBuilder();
		$qb->select('a')
		   ->from('Article', 'a')
		   ->add('orderBy', 'a.published DESC')
		   ->setMaxResults(5);

		$query = $qb->getQuery();

		return $query;
	}

}
