<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ArticleRepository extends EntityRepository
{
	public function findSoMuchFormTheLast($min, $max)
	{
		$qb = $this->createQueryBuilder('a')
		->orderBy('a.published', 'DESC')
		->setFirstResults($min)
		->setMaxResults($max)
		->getQuery()
		->getResult()
		;

		return $qb;
	}

}
