<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
	public function findAllInArray()
	{
		$qb = $this->createQueryBuilder('g')
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}
}
