<?php

namespace AppBundle\Repository;

/**
 * GameCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
