<?php

namespace AppBundle\Repository;

/**
 * HistoryFillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryFillRepository extends \Doctrine\ORM\EntityRepository
{
}
