<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessengerRepository extends EntityRepository
{
	public function findAllByInstanceInArray($user, $receiver)
	{
		$qb = $this->createQueryBuilder('m')
		->andwhere('m.author = ?1 AND m.receiver = ?2 OR m.author = ?2 AND m.receiver = ?1')
		->setParameter('1', $user)
		->setParameter('2', $receiver)
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}

	public function findOneByInArray($id)
	{
		$qb = $this->createQueryBuilder('m')
		->where('m.id = :id')
		->setParameter('id', $id)
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}
}