<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{

	public function findAllByAuthorInArray($user)
	{
		$qb = $this->createQueryBuilder('m')
		->where('m.author = :user')
		->setParameter('user', $user)
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}

	public function findAllByReceiverInArray($user)
	{
		$qb = $this->createQueryBuilder('m')
		->where('m.receiver = :user')
		->setParameter('user', $user)
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}

	public function findOneByInArray($id)
	{
		$qb = $this->createQueryBuilder('m')
		->where('m.id = :id')
		->setParameter('id', $id)
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}
}
