<?php

namespace AppBundle\Repository;

/**
 * MessengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessengerRepository extends \Doctrine\ORM\EntityRepository
{
}
