<?php

namespace AppBundle\Repository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneInArray($id)
	{
		$qb = $this->createQueryBuilder('p')
		->join('p.user', 'u')
		->addSelect('u.username')
		->where('p.id = :id')
		->setParameter('id', $id)
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}
}
