<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findOneInArray($id)
	{
		$qb = $this->createQueryBuilder('u')
		->join('u.profile', 'p')
		->addSelect('p')
		->leftJoin('u.games', 'g')
		->addSelect('g')
		->where('u.id = :id')
		->setParameter('id', $id)
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}

	public function findSessionInArray($id)
	{
		$qb = $this->createQueryBuilder('u')
		->join('u.profile', 'p')
		->addSelect('p')
		->join('u.games', 'g')
		->addSelect('g')
		->where('u.id = :id')
		->setParameter('id', $id)
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}

	public function findFriendByCurrentUserIdInArray($id)
	{
		$qb = $this->createQueryBuilder('u')
		->leftJoin('u.myFriend', 'f')
		->addSelect('f')
		->where('u.id = :id')
		->setParameter('id', $id)
		->getQuery()
		->getArrayResult()
		;

		return $qb;
	}
}
