imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['en'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    # serializer: { enabled: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Easy admin Configuration
easy_admin:
    site_name: '<span style="color: #2C2C2C;">Brothers In Games</span>'
    design:
        menu:
            - { entity: 'article', label: 'Articles', icon: 'file' }
            - { entity: 'game', label: 'Jeux', icon: 'gamepad' }
            - { entity: 'gameCategory', label: 'Catégories de jeu', icon: 'tags' }
            - { entity: 'user', label: 'Utilisateurs', icon: 'user' }
            - { entity: 'profile', label: 'Profile utilisateurs', icon: 'th-list ' }
            - { entity: 'announcement', label: 'Annonces', icon: 'bullhorn' }
        brand-color: '#EC9C34'
        assets:
            css:
                - 'admin/easyAdmin.css'
    list:
        max_results: 30
        actions:
            - { name: 'new', label: 'Nouveau' }
            - { name: 'edit', label: 'Modifier' }
            - { name: 'search', label: 'Rerchercher' }
            - { name: 'delete', label: 'supprimer' }
    entities:
        game:
            class: AppBundle\Entity\Game
            list:
                title: "Liste des jeux"
                fields:
                    - id
                    - { property: 'cover', label: 'Couverture', type: 'image'}
                    - { property: 'title', label: 'Titre' }
                    - slug
                    - { property: 'announcements', label: 'Annonces' }
                    - { property: 'gamecategories', label: 'Categories'}
            form:
                title: "Edition d'un jeux"
                fields:
                    - { property: 'title', label: 'Titre' }
                    - slug
                    - { property: 'gamecategories', label: 'Categories' }
                    - { property: 'cover', label: 'Couverture', type: 'url'}

        gameCategory:
            class: AppBundle\Entity\GameCategory
            list:
                title: "Liste des catégories de jeu"
                fields:
                    - id
                    - { property: 'title', label: 'Titre' }
                    - slug
                    - { property: 'games', label: 'Jeux' }
            form:
                title: "Edition d'une catégorie"
                fields:
                    - { property: 'title', label: 'Titre' }
                    - slug
        user:
            class: AppBundle\Entity\User
            list:
                title: "Liste des utilisateurs"
                actions: ['-new', '-delete']
                fields:
                    - id
                    - { property: 'username', label: 'Pseudo' }
                    - profile
                    - { property: 'mail', label: 'E-Mail' }
                    - { property: 'announcements', label: 'Annonces' }
                    - { property: 'articles', label: 'Articles' }
                    - role
                    - { property: 'isActive', label: 'Activation'}

            form:
                title: "Edition d'un utilisateur"
                fields:
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'mail', label: 'E-Mail' }
                    - { property: 'isActive', label: 'Activation'}
                    - role
        profile:
            class: AppBundle\Entity\Profile
            list:
                title: "Liste des profile utilisateurs"
                actions:
                    - '-new'
                    - '-delete'
                fields:
                    - id
                    - { property: 'user', label: 'Pseudo' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'image', label: 'Avatar', type: 'image' }
                    - { property: 'birthdate', label: 'Date de naissance' }
                    - { property: 'gender', label: 'Genre'}

            form:
                title: "Edition d'un profile utilisateur"
                fields:
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'image', label: 'Avatar', type: 'url' }
                    - { property: 'birthdate', label: 'Date de naissance' }
                    - { property: 'gender', label: 'Genre'}
                    - { property: 'description', label: 'Description'}
        article:
            class: AppBundle\Entity\Article
            list:
                title: "Liste des articles"
                fields:
                    - id
                    - { property: 'image', label: 'Image', type: 'image' }
                    - { property: 'user', label: 'Autheur' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'content', label: 'Contenu' }
                    - { property: 'published', label: 'Date de publication' }

            form:
                title: "Edition d'un article"
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'user', label: 'Autheur' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'image', label: 'Image', type: 'url' }
                    - { property: 'content', label: 'Contenu'}
                    - { property: 'published', label: 'Date de publication' }
        announcement:
            class: AppBundle\Entity\Announcement
            list:
                title: "Liste des annonces"
                fields:
                    - id
                    - { property: 'game', label: 'Jeux' }
                    - { property: 'user', label: 'Autheur' }
                    - { property: 'content', label: 'Contenu' }
                    - { property: 'published', label: 'Date de publication' }
            form:
                title: "Edition d'un annonce"
                fields:
                    - { property: 'game', label: 'Jeux' }
                    - { property: 'user', label: 'Autheur' }
                    - { property: 'content', label: 'Contenu' }
                    - { property: 'published', label: 'Date de publication' }
