imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['fr'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    # serializer: { enabled: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        # auto_generate_proxy_classes: false
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Easy admin Configuration
easy_admin:
    translation_domain: 'admin'
    site_name: '<span style="color: #2C2C2C;">Brothers In Games</span>'
    design:
        menu:
            - { label: 'Homepage', url: '../' }
            - { entity: 'game', icon: 'gamepad' }
            - { entity: 'article', icon: 'file' }
            - { entity: 'gameCategory', icon: 'tags' }
            - { entity: 'user', icon: 'user' }
            - { entity: 'profile', icon: 'th-list ' }
            - { entity: 'announcement', icon: 'bullhorn' }
        brand-color: '#EC9C34'
        assets:
            css:
                - 'admin/easyAdmin.css'
    list:
        max_results: 30
    entities:
        game:
            class: AppBundle\Entity\Game
            list:
                title: 'Liste des jeux'
                fields:
                    - id
                    - { property: 'cover', type: 'image'}
                    - title
                    - slug
                    - announcements
                    - gamecategories
            form:
                title: "Edition d'un jeux"
                fields:
                    - title
                    - slug
                    - gamecategories
                    - { property: 'cover', label: 'Couverture', type: 'url'}

        gameCategory:
            class: AppBundle\Entity\GameCategory
            list:
                title: 'Liste des catégories de jeu'
                fields:
                    - id
                    - title
                    - slug
                    - games
            form:
                title: "Edition d'une catégorie"
                fields:
                    - title
                    - slug
        user:
            class: AppBundle\Entity\User
            list:
                title: 'Liste des utilisateurs'
                actions: 
                    - '-new'
                    - '-delete'
                fields:
                    - id
                    - username
                    - profile
                    - mail
                    - announcements
                    - articles
                    - role
                    - isActive
            show:
                actions: ['-delete']
                fields:
                    - id
                    - username
                    - profile
                    - mail
                    - role
            form:
                title: "Edition d'un utilisateur"
                actions: ['-delete']
                fields:
                    - username
                    - mail
                    - isActive
                    - role
        profile:
            class: AppBundle\Entity\Profile
            list:
                title: 'Liste des profile utilisateurs'
                actions:
                    - '-new'
                    - '-delete'
                fields:
                    - id
                    - user
                    - firstname
                    - image
                    - birthdate
                    - gender
            show:
                actions: ['-delete']
            form:
                title: "Edition d'un profile utilisateur"
                actions: ['-delete']
                fields:
                    - firstname
                    - image
                    - birthdate
                    - gender
                    - description
        article:
            class: AppBundle\Entity\Article
            list:
                title: 'Liste des articles'
                fields:
                    - id
                    - { property: 'image', type: 'image' }
                    - user
                    - title
                    - content
                    - published

            form:
                title: "Edition d'un article"
                fields:
                    - title
                    - user
                    - slug
                    - image
                    - content
                    - published
        announcement:
            class: AppBundle\Entity\Announcement
            list:
                title: 'Liste des annonces'
                fields:
                    - id
                    - game
                    - user
                    - content
                    - published
            form:
                title: "Edition d'une annonce"
                fields:
                    - game
                    - user
                    - content
                    - published
