app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

api:
    path: /api
    defaults: { _controller: AppBundle:Game:getApi }
    options:
        expose: true
#---------------------- Home
home_visitor:
    path: /
    defaults: { _controller: AppBundle:Home:homeVisitor }
    options:
        expose: true
home_user:
  path: /home
  defaults: { _controller: AppBundle:Home:homeUser }
  options:
        expose: true

#---------------------- User
signup:
    path: /user/create
    defaults: { _controller: AppBundle:User:create }
    methods: [POST]
    options:
        expose: true
login:
    path: /connection
    defaults: { _controller: AppBundle:User:login }
    options:
        expose: true
logout:
    path: /logout
    options:
        expose: true
account_show:
    path: /account
    defaults: { _controller: AppBundle:User:read }
    options:
        expose: true
account_update:
    path: /account/update
    defaults: { _controller: AppBundle:User:update }
    options:
        expose: true

#---------------------- Friend
friends_list:
    path: /friends
    defaults: { _controller: AppBundle:Friend:list }
    options:
        expose: true

#---------------------- Profile
profile_show:
    path: /profile/{slug}
    defaults: { _controller: AppBundle:Profile:otherProfileShow }
    options:
        expose: true
my_profile_show:
    path: /my-profile
    defaults: { _controller: AppBundle:Profile:show }
    options:
        expose: true
my_profile_update:
    path: /my-profile/update
    defaults: { _controller: AppBundle:Profile:update }

#---------------------- Mail
mail_list_receive:
    path: /mail/receive
    defaults: { _controller: AppBundle:Mail:listReceive }
    options:
        expose: true
mail_list_send:
    path: /mail/send
    defaults: { _controller: AppBundle:Mail:listSend }
    options:
        expose: true
mail_show:
    path: /mail/show/{id}
    defaults: { _controller: AppBundle:Mail:read }
    options:
        expose: true

#---------------------- Messenger
messenger_show:
    path: /messenger/{id}
    defaults: { _controller: AppBundle:Messenger:read }
    options:
        expose: true
messenger_list:
    path: /messenger
    defaults: { _controller: AppBundle:Messenger:list }
    options:
        expose: true

#---------------------- Announcements
announcements_list:
    path: /announcements
    defaults: { _controller: AppBundle:Announcement:list }
    options:
        expose: true
announcements_list_game:
    path: /announcements/{slug}
    defaults: { _controller: AppBundle:Announcement:list }
    options:
         expose: true
announcements_show:
    path: /announcement/{id}/{slug}
    defaults: { _controller: AppBundle:Announcement:read }
    options:
        expose: true
announcements_create:
    path: /announcement/create
    defaults: { _controller: AppBundle:Announcement:create }
    methods: [POST]
    options:
        expose: true

#---------------------- Games
games_list:
    path: /games
    defaults: { _controller: AppBundle:Game:list }
    options:
        expose: true
my_games:
    path: /my-games
    defaults: { _controller: AppBundle:Game:listByUser }
    options:
        expose: true

#---------------------- News
article_show:
    path: /article/{id}/{slug}
    defaults: { _controller: AppBundle:Article:read }
    options:
        expose: true


###########################
# Récupération des donnée #
###########################

#---------------------- News
# Get articles data
# Return JSON data
# No need parameters
get_home_articles:
    path: /get/home/articles
    defaults: { _controller: AppBundle:Article:getHomeArticle }
    options:
        expose: true

# Get articles data for the home right sidebar
# Return JSON data
# No need parameters
get_sidebar_articles:
    path: /get/home/articles/sidebar
    defaults: { _controller: AppBundle:Article:getHomeArticleSidebar }
    options:
        expose: true

# Get data to the article currently selected
# Return JSON data
# need ID of this article sending by post method
get_article:
    path: /get/home/article
    defaults: { _controller: AppBundle:Article:getArticle }
    options:
        expose: true

#---------------------- Games
# Get games data
# Return JSON data
# No need parameters
get_all_games:
    path: /get/games
    defaults: { _controller: AppBundle:Game:getAllGames }
    options:
        expose: true

# Get games data from the current user
# Return JSON data
# No need parameters
get_user_games:
    path: /get/user/games
    defaults: { _controller: AppBundle:Game:getUserGame }
    options:
        expose: true

#---------------------- Announcements
# Get announcements data
# Return JSON data
# No need parameters
get_all_announcement:
    path: /get/announcements
    defaults: { _controller: AppBundle:Announcement:getAllAnnouncements }
    options:
        expose: true

# Get announcements data filtered by game
# Return JSON data
# need SLUG of the concerned game sending by post method
get_announcement_by_game:
    path: /get/announcements/games
    defaults: { _controller: AppBundle:Announcement:getAnnouncementByGameSlug }
    options:
        expose: true

# Get data to the announcement currently selected
# Return JSON data
# need ID of this announcement sending by post method
get_announcement:
    path: /get/announcement
    defaults: { _controller: AppBundle:Announcement:getAnnouncement }
    options:
        expose: true

#---------------------- Profile
# Get profile data to the current user
# Return JSON data
# No need parameters
get_profile:
    path: /get/profile
    defaults: { _controller: AppBundle:Profile:getProfile }
    options:
        expose: true

#---------------------- User
# Get current user data
# Return JSON data
# No need parameters
get_user:
    path: /get/user
    defaults: { _controller: AppBundle:User:getUser }
    options:
        expose: true