app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

home_visitor:
    path: /
    defaults: { _controller: AppBundle:Home:homeVisitor }
    options:
        expose: true
home_user:
  path: /home
  defaults: { _controller: AppBundle:Home:homeUser }
  options:
        expose: true

signup:
    path: /user/create
    defaults: { _controller: AppBundle:User:create }
    methods: [POST]
    options:
        expose: true
login:
    path: /connection
    defaults: { _controller: AppBundle:User:login }
    options:
        expose: true
logout:
    path: /logout
    options:
        expose: true

games_list:
    path: /games
    defaults: { _controller: AppBundle:Game:list }
    options:
        expose: true

announcements_list:
    path: /annoucements
    defaults: { _controller: AppBundle:Announcement:list }
    options:
        expose: true

# Récupération des donnée
get_home_articles:
    path: /home/get/articles
    defaults: { _controller: AppBundle:Article:getHomeArticle }
    options:
        expose: true

get_sidebar_articles:
    path: /home/get/articles/sidebar
    defaults: { _controller: AppBundle:Article:getHomeArticleSidebar }
    options:
        expose: true

get_all_games:
    path: /games/get
    defaults: { _controller: AppBundle:Game:getAllGames }
    options:
        expose: true
    