AppBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 4
                minMessage: 'Your first name must be at least {{ limit }} characters long'
        mail:
            - NotBlank: ~
            - Email: 
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
        password:
            - NotBlank: ~
            - Length:
                min: 6
                minMessage: 'Your first name must be at least {{ limit }} characters long'