AppBundle\Entity\Announcement:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AnnouncementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        published:
            type: datetime
    manyToOne:
        game:
            targetEntity: Game
            inversedBy: announcements
            joinColumn:
                name: game_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: announcements
            jointColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
