AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        published:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            inversedBy: articles
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
