AppBundle\Entity\Friend:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\FriendRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user1:
            targetEntity: User
            inversedBy: friend1
            joinColumn: 
                name: user1_id
                referencedColumnName: id
        user2:
            targetEntity: User
            inversedBy: friend2
            joinColumn: 
                name: user2_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
