AppBundle\Entity\GameCategory:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GameCategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        apiId:
            type: integer
            nullable: true
        title:
            type: string
            length: '45'
            unique: true
        slug:
            type: string
            length: '45'
    manyToMany:
        games:
            targetEntity: Game
            mappedBy: gamecategories
    lifecycleCallbacks: {  }
