AppBundle\Entity\Game:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        cover:
            type: string
            length: 255
            nullable: true
    manyToMany:
        gamecategories:
            targetEntity: GameCategory
            inversedBy: games
            joinTable:
                name: game_has_gamecategory
                joinColumns:
                    game_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    gamecategory_id:
                        referencedColumnName: id
        users:
            targetEntity: User
            mappedBy: games
    oneToMany:
        announcements:
            targetEntity: Announcement
            mappedBy: game
    lifecycleCallbacks: {  }
