AppBundle\Entity\Message:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MessageRepository
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        published:
            type: datetime
    manyToOne:
        receiver:
            targetEntity: User
            inversedBy: messageRead
            joinColumn: 
                name: receiver_id
                referencedColumnName: id
        author:
            targetEntity: User
            inversedBy: messageSend
            joinColumn: 
                name: author_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
