AppBundle\Entity\Messenger:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MessengerRepository
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        published:
            type: datetime
    manyToOne:
        receiver:
            targetEntity: User
            inversedBy: messengerRead
            joinColumn: 
                name: receiver_id
                referencedColumnName: id
        author:
            targetEntity: User
            inversedBy: messengerSend
            joinColumn: 
                name: author_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
