AppBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '45'
            unique: true
        code:
            type: string
            length: '45'
            unique: true
    oneToMany:
        users:
            targetEntity: User
            mappedBy: role
    lifecycleCallbacks: {  }
