AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 45
            unique: true
        mail:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        isActive:
            type: boolean  
    oneToOne:
        profile:
            targetEntity: Profile
            inversedBy: user
            joinColumn:
                name: profile_id
                referencedColumnName: id
    manyToMany:
        games:
            targetEntity: Game
            inversedBy: users
            joinTable:
                name: user_has_game
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    game_id:
                        referencedColumnName: id
        me:
            targetEntity: User
            mappedBy: myFriend
            
        myFriend:
            targetEntity: User
            inversedBy: me
            joinTable:
                name: friend
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    friend_id:
                        referencedColumnName: id
    manyToOne:
        role:
            targetEntity: Role
            inversedBy: users
            joinColumn:
                name: role_id
                referencedColumnName: id
    oneToMany:
        announcements:
            targetEntity: Announcement
            mappedBy: user
        articles:
            targetEntity: Article
            mappedBy: user
        messengerRead:
            targetEntity: Messenger
            mappedBy: receiver        
        messengerSend:
            targetEntity: Messenger
            mappedBy: author        
        messageRead:
            targetEntity: Message
            mappedBy: receiver        
        messageSend:
            targetEntity: Message
            mappedBy: author        
    lifecycleCallbacks: {  }
